import type { ThemeName, ThemeTokens } from '../types';

export const COLORS = {
  bg: '#F7F6F3',
  surface: '#FFFFFF',
  surfaceSecondary: '#ECE8E2',
  text: '#111111',
  textSecondary: '#666666',
  textMuted: '#999999',
  gold: '#C8A65A',
  goldLight: '#DFC27A',
  goldDark: '#A88840',
  goldMuted: 'rgba(200, 166, 90, 0.12)',
  navy: '#132238',
  navyLight: '#1E3451',
  navyMuted: 'rgba(19, 34, 56, 0.05)',
  border: 'rgba(17, 17, 17, 0.06)',
  borderLight: '#F0EDE8',
  success: '#2D6A4F',
  error: '#B22234',
  warning: '#D4A017',
};

export const FONTS = {
  display: '"Playfair Display", Georgia, "Times New Roman", serif',
  heading: '"Playfair Display", Georgia, "Times New Roman", serif',
  body: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  mono: '"JetBrains Mono", "Fira Code", Consolas, monospace',
  arabicDisplay: '"Alexandria", "Noto Kufi Arabic", sans-serif',
  arabicBody: '"IBM Plex Sans Arabic", "Tajawal", sans-serif',
};

export const LIGHT_LUXURY_THEME: ThemeTokens = {
  colors: {
    gold: COLORS.gold,
    goldLight: COLORS.goldLight,
    goldDark: COLORS.goldDark,
    goldMuted: COLORS.goldMuted,
    navy: COLORS.navy,
    navyLight: COLORS.navyLight,
    white: COLORS.surface,
    background: COLORS.bg,
    backgroundSecondary: COLORS.surfaceSecondary,
    surface: COLORS.surface,
    warm: COLORS.surfaceSecondary,
    graphite: COLORS.text,
    grey: COLORS.textSecondary,
    border: COLORS.border,
    borderHover: 'rgba(17, 17, 17, 0.12)',
    success: COLORS.success,
    error: COLORS.error,
    warning: COLORS.warning,
    info: COLORS.gold,
  },
  typography: {
    headingFont: FONTS.display,
    bodyFont: FONTS.body,
    arabicHeadingFont: FONTS.arabicDisplay,
    arabicBodyFont: FONTS.arabicBody,
  },
  spacing: {
    '0': '0',
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '8': '2rem',
    '10': '2.5rem',
    '12': '3rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '32': '8rem',
    '40': '10rem',
  },
  shadows: {
    xs: '0 1px 2px rgba(10, 22, 40, 0.04)',
    sm: '0 2px 8px rgba(10, 22, 40, 0.04)',
    md: '0 4px 24px rgba(10, 22, 40, 0.04)',
    lg: '0 12px 40px rgba(10, 22, 40, 0.08)',
    xl: '0 24px 48px rgba(10, 22, 40, 0.12)',
    gold: '0 4px 24px rgba(200, 166, 90, 0.25)',
    glass: '0 8px 32px rgba(0, 0, 0, 0.06)',
  },
  radii: {
    none: '0',
    sm: '1px',
    md: '2px',
    lg: '4px',
    xl: '8px',
    full: '9999px',
  },
  breakpoints: {
    mobile: '0',
    tablet: '640px',
    desktop: '1024px',
    wide: '1440px',
  },
  zIndex: {
    base: 0,
    elevated: 10,
    dropdown: 100,
    sticky: 500,
    overlay: 1000,
    modal: 2000,
    toast: 3000,
    loader: 9999,
  },
  transitions: {
    fast: '150ms',
    base: '250ms',
    slow: '400ms',
    slower: '800ms',
  },
};

export const THEMES: Record<ThemeName, ThemeTokens> = {
  'light-luxury': LIGHT_LUXURY_THEME,
  'dark-premium': LIGHT_LUXURY_THEME,
  presentation: LIGHT_LUXURY_THEME,
};
